sudo: required
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script: yarn add polymer-cli
script:
  - xvfb-run wct --module-resolution=node --npm --skip-plugin sauce
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --module-resolution=node --npm --plugin sauce --skip-plugin local; fi'
after_success:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET" -in deploy.enc -out deploy_key -d; fi'
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
env:
  global:
    - secure: TU2loewaGr36wIu96Xh2aN4/e32ui8L7WZvqtaInZirHXpUUczLR4NWPP+b2pvMJGCTBRMVRMaAsGXYhNuyWW8y3AVvjTYG+qcH7CRv/LT7kHPHPzTJiH0lYwB9wDXJnKj1SqsoqFWNBb706rlVKZzz4xYWSbFUCsn2xLjrIAaxTQXScYM7iXLanZhr5d07LXiMTu0t5iYLOOnGmhx5Of+nnDcyshr8GXFs2Rt4vtCZ09c4vQEQ9i2leeOxRklYnTvGYRUhdAnk51aJRXaUPCDG1ZHIeqQaLqgtkUxYRG0QhxFok1WgTp0lAToJI6LFQqUWyo6CEQ6JHJE9RNcE/PxrttlNQR4bTGTTET1GzTw3DWZr2uabdQN6rOJXxNFKvEkCaWx2d23S0aAcqfjpgNVabMtzMiAHxCc1esB5a+/od/9kRMVTvl/w9Cp9DIxxy5udB/8tRpVMXbO/ZMZ+l3koItIjY599gIqMzL71fQf4irH7AiYBbwolPmdDdGnniPCKToBym0BxMXZHaFw9gAa/dJzoRFBGRp25mBAKFPZy59ulpmN1vCQDD0R5OL2CCV5We+eIajqW2Xe0UcWveyAN/TC9K40VOgcGOFg+HuZP9jLyysal2iT6ALzmSe/w2wVub/POr0v2qRC4T4s5suS5Un6K2+2Z9JTw9mOi+CUw=
    - secure: k7SPZ6ug35aBDhBk/dBN5K2cdunEvCpFRHfGEtdIw4feqbJziljoJiU3Zu2lbxmgYLHWq7oAZe1ztpTNnG/crJyO1966KSHpdv2TNqBwrIfjCxU7Y+KTPrDe1nnI3zrcYsP2uFlhh/3sSShq6+Yky1tn8TpBemdRu9LUJ9mOMQBtoACCbK2VeiCZNAPP2UnplcrD3LiFl5rbSTHe6QZq/qIl3XrcTrTruxtw3t9lszZ79n6yyVdfF2nXkiIIM4Sa7z/ow6ULAPX1MzPP7AB5bDw0XY28gTeYp2pxP9dNjbfDmr1kpB49/BsFLe3WDsXxEP2VdZgWGsphQaY8h9auFQD1h67T0a6kBau0ntm8gy1qx4njBwORngbvXVD8DtEssxsFW9clb4knQSn+ZUMXHxGWlWkEWGETy7ptGloB5TITBgHgVZWmcqICX+wjIp8eNx+Nfc3GKUjWodpwhNvyzNCb4kb1yCG32rbj8M8YC9XQ5T+Oe2aqhniRIYGu9ydlf2fM/bOObob/FDgQU1jwtFWir6Sta8wkub96TlglzN9/8lE1WnUW36tb3j2MJX3aYHbyU3+RjliIHeXhY5NnAdZbTbNDlT5mkUJa1EQOb6Qscy/cj6PaCuoBsiwTA9XOibt0IkMT5Ir/1nziZqgkZhjhYgdzOZHntE/1GrtqJiw=
    - secure: FP7JSFtS0ZPKPUMksF3szfbVrwNQmz/O/4vttJkDurZn2q4b7zjXfdREct/KF/8gXD4XSMvkf+HcWtukX4CDFX1JbsNvAZ0/9/XXMG/FGVoyG5zKv3RM4tUPrXAQSq6EUYfGY4xBBRE0C15EXwcSqtZ7BUE49meXenQbR4jGkOM5JXjKhAPe9lnovmGGDxGKM1MNrH2Lmgs9u36n8imvpaMMNl1XiHqh+mKgQg3/d/ssXXfUZGg++/7z8EnqKzki1Ph07Ip9BqodTbSXnda7NX+QQ06VR6F+lZA9iyApx9hOv2Nlfoi3Hg8erVfYILPTCdHQXn0CTWnGKToM9VS5gSVUrZ4TxU7kmVRmueZGFbP4+GqmSMlFduy/jVtLoVBH6WUyOVNzv6Z5LGKEs/2dVReP3Jvp+Zoo0ruNVEGalmV/X1eVJouRKVzm/ftT2uIgfsXr5X9zG/eodTsFZggcUJappK9azJEMydu0dMH2onVxbvri3qIBqZpAPvvRdODarfQ2RvResuDbI+HS9hSpW+X4WjLqT7VTji6QrNdDREErMPHixnF2FXZdbevC7lxiJkqH3MDQkQMG35eNjqEekCHzkrdwEAy89DTfggTq1KW0+fM0N/q/vxYfj0HOjaCgM7hkjYiy86L3hayUDLoqCyPfym7m1nyJ1yayyNR4V0Q=
    - secure: YhuzikAqLixazpELcQsomF6EGFll2/zZuxdkpHdic28onqdY8VgMPuFnY3sHiYLL2ruqPIuWNvGXwnUQHgz6MvBVDjBlkRR9G0w1uRyzJ7nWnzFBOPvPTNnvZo9qcz1Yflo70VkslxWpERQeMbj6zgom5GpM7bNWrgpvAZ7Q1ec+QfwB/9m+xgTevRwuM+MzIa2OvYAlE9pVs4yMTO/w5m1YsIQiZnmquhxt5CVrhFxUS3RWSJKJ20PY3R3qPpwD7fge1MoAQUUgfDgtqP3b0e8G3DxiYKfvxhe+syW85MFwYH7b4sugBoOdwO81UK6C1JpPCX156lZp6pUdzaMQdjZz1+g5SjlY2oSmmBOMuQLyfayPmbeuVtusgfB3M9+/YeB6/tqQctsjijWrmrRl9HRVmpAU7uqXYr9sq+AOIOVtXxeprQRxvBI1ZsjeT6+0eS9PRcTgtH0UJMBNg+wddIaEalna5inGZGZ643Leq4jOO+qcBMv0MIuzL+B/buec4Hwt338Tusc8LKmk8zJWgXSi/d27UKUN6OnBSj0RSmL8aWkaKtGnpJkxsQXlOgCvEqzv1s7HnNqWx3hhAogVSgj/ENjCae/0ANOSecdz+ICebQkENNfcEvsz0tMhARBxYoLNclSDa8fdUT9ZO1wSqgKFOUS4yfSWUvM3ApMpTvE=

